review3 = Review.create(name: 'EIT 2019')

sections = [
	['Section I: Drawing Production', 'Reviewer'], 
	['Section II: Design', 'Reviewer'], 
	['Section III: Contract Administration', 'Reviewer'],
	['Section IV: Project Management', 'Reviewer'],
	['Section V: Organization and Health Safety', 'Reviewer'],
	['Section VI: Overall Performance', 'Reviewer'],
	['Employee Section', 'Employee']
]

# example question
# ['Section I: Drawing Production', 'Drawing', 'Creates drawings in accordance with CEL standards', 'check_box', [1, 2, 3]]

# will need to create the 7th job_level

questions = [
	['Section I: Drawing Production', 'Drawing', 'Creates drawings in accordance with CEL standards', 'check_box', [1, 2, 3, 4, 5]],
	['Section I: Drawing Production', 'Drawing', 'Drawing tagging is complete', 'check_box', [1, 2, 3, 4, 5]],
	['Section I: Drawing Production', 'Drawing', 'Drawing presentation is neat and tidy', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Drawing', 'Able to follow technical instructions for drawings', 'check_box', [1, 2, 3, 4, 5]],
	['Section I: Drawing Production', 'Drawing', 'Asks questions when appropriate', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Drawing', 'Reviews work to ensure it is complete and technically accurate', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Drawing', 'Follows CEL standards for filing design and archiving material as appropriate ', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Drawing', 'Understands project objectives and scope', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Drawing', 'Managing Principal Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Drawing', 'Employee Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Production', 'Meets required deadlines for work assigned', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Production', 'Identifies that assigned work cannot be completed within alloted timeframe', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Production', 'Managing Principal Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Production', 'Employee Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Layout', "Able to implement layouts in accordance to PM's direction", 'check_box', [1]],
	['Section I: Drawing Production', 'Layout', "Makes layout decisions and coordinates with other services", 'check_box', [2, 3]],
	['Section I: Drawing Production', 'Layout', "Provides designers with direction on implementing concept(s)", 'check_box', [4, 5, 6, 7]],
	['Section I: Drawing Production', 'Layout', "Provides direction for 3D coordination of services", 'check_box', [4, 5, 6, 7]],
	['Section I: Drawing Production', 'Layout', 'Managing Principal Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section I: Drawing Production', 'Layout', 'Employee Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section II: Design', 'Calculations', "Performs load calculations accurately", 'check_box', [2, 3, 4]],
	['Section II: Design', 'Calculations', "Reviews load calculations and ensures accuracy", 'check_box', [5, 6, 7]],
	['Section II: Design', 'Calculations', "Performs lighting calculations", 'check_box', [2, 3, 4, 5, 6]],
	['Section II: Design', 'Calculations', "Performs voltage drop calculations", 'check_box', [2, 3, 4, 5, 6]],
	['Section II: Design', 'Calculations', "Performs fault calculations", 'check_box', [2, 3, 4, 5, 6, 7]],
	['Section II: Design', 'Calculations', "Reviews lighting calculations", 'check_box', [5, 6, 7]],
	['Section II: Design', 'Calculations', "Reviews voltage drop calculations", 'check_box' , [5, 6, 7]],
	['Section II: Design', 'Calculations', "Reviews fault calculations", 'check_box', [5, 6, 7]],
	['Section II: Design', 'Calculations', "Performs building air balance/building pressurization calculations", 'check_box', [2, 3, 4, 5, 6]],
	['Section II: Design', 'Calculations', "Reviews building air balance/building pressurization calculations", 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Calculations', "Reviews for compliance with OBC SB-10 and/or ASHRAE 90.1", 'check_box', [4, 5, 6, 7]],
	['Section II: Design', 'Calculations', "Performs static pressure/back-pressure/pump head pressure calculations", 'check_box', [2, 3, 4, 5, 6]],
	['Section II: Design', 'Calculations', "Reviews static pressure/back-pressure/pump head pressure calculations", 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Calculations', "Performs gas pipe sizing", 'check_box', [2, 3]],
	['Section II: Design', 'Calculations', "Reviews gas pipe sizing", 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Calculations', "Performs plumbing load calculations ", 'check_box', [3, 4, 5, 6]],
	['Section II: Design', 'Calculations', "Reviews plumbing load calculations", 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Calculations', "Knowledge of related codes, regulations and standards", 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Calculations', 'Managing Principal Comments', 'text', [2, 3, 4, 5, 6, 7]],
	['Section II: Design', 'Calculations', 'Employee Comments', 'text', [2, 3, 4, 5, 6, 7]],
	['Section II: Design', 'System (choice of)', "Ability to create and document conceptual design in the respective discipline", 'check_box', [6, 7]],
	['Section II: Design', 'System (choice of)', "Leads and supervises the project team with design and drafting of mechanical/electrical systems", 'check_box', [6, 7]],
	['Section II: Design', 'System (choice of)', "Assists with choice of system ", 'check_box', [6, 7]],
	['Section II: Design', 'System (choice of)', "Type of System ", 'check_box', [6, 7]],
	['Section II: Design', 'System (choice of)', "Able to choose appropriate system for the application and create system", 'check_box', [6, 7]],
	['Section II: Design', 'System (choice of)', "Implements conceptual design with minimal input", 'check_box', [6, 7]],
	['Section II: Design', 'System (choice of)', "Creates conceptual design with minimal input", 'check_box', [7]],
	['Section II: Design', 'System (choice of)', 'Managing Principal Comments', 'text', [6, 7]],
	['Section II: Design', 'System (choice of)', 'Employee Comments', 'text', [6, 7]],
	['Section II: Design', 'Equipment Selection', 'Inputs equipment into drawings ', 'check_box', [1, 2]],
	['Section II: Design', 'Equipment Selection', 'Requests equipment cut sheet from vendor ', 'check_box', [3, 4]],
	['Section II: Design', 'Equipment Selection', 'Prepares equipment schedule ', 'check_box', [3, 4]],
	['Section II: Design', 'Equipment Selection', 'Selects type of equipment ', 'check_box', [5, 6]],
	['Section II: Design', 'Equipment Selection', "Managing Principal Comments", 'text', [1, 2, 3, 4, 5, 6]],
	['Section II: Design', 'Equipment Selection', 'Employee Comments', 'text', [1, 2, 3, 4, 5, 6]],
	['Section II: Design', 'Design Reports and Studies', 'Formatting - grammatically correct and accurate spelling', 'check_box', [3, 4, 5, 6]],
	['Section II: Design', 'Design Reports and Studies', 'Clear and concise', 'check_box', [3, 4, 5, 6]],
	['Section II: Design', 'Design Reports and Studies', 'Written at level of client expectations ', 'check_box', [3, 4, 5, 6]],
	['Section II: Design', 'Design Reports and Studies', 'Reviews existing conditions', 'check_box', [3, 4, 5, 6]],
	['Section II: Design', 'Design Reports and Studies', 'Identifies issues', 'check_box', [3, 4, 5, 6]],
	['Section II: Design', 'Design Reports and Studies', 'Makes recommendations', 'check_box', [3, 4, 5, 6]],
	['Section II: Design', 'Design Reports and Studies', 'Able to create a DBM', 'check_box', [ 6]],
	['Section II: Design', 'Design Reports and Studies', 'Able to review quantities against DBMs', 'check_box', [6]],
	['Section II: Design', 'Design Reports and Studies', 'Able to develop DBMs with minimal input', 'check_box', [7]],
	['Section II: Design', 'Design Reports and Studies', 'Able to determine if pricing is reasonable with minimal supervision', 'check_box', [7]],
	['Section II: Design', 'Design Reports and Studies', "Managing Principal Comments", 'text', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Design Reports and Studies', 'Employee Comments', 'text', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', 'Able to read specifications and review shop drawings ', 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', 'Assemble appropriate sections', 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', "Eliminate items that don't apply", 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', 'Revise specifications for specific job to ensure all items are covered', 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', 'Equipment grade is appropriate for the project', 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', 'Submits in a timely manner', 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', 'Schedule for all equipment included', 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', 'Schedule information in a timely manner', 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', 'Schedules are complete and accurate', 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', 'Able to create specification section ', 'check_box', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', "Managing Principal Comments", 'text', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Specifications', 'Employee Comments', 'text', [3, 4, 5, 6, 7]],
	['Section II: Design', 'Coordination', 'Responsible for coordinating with all disciplines for the work that is being performed', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section II: Design', 'Coordination', 'Able to comprehend typical coordination issues', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section II: Design', 'Coordination', 'Asks appropriate questions', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section II: Design', 'Coordination', 'Attends and actively participates in internal coordination meetings', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section II: Design', 'Coordination', 'Provides accurate technical information to other disciplines in a timely manner ', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section II: Design', 'Coordination', 'Identifies issues and provides solutions', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section II: Design', 'Coordination', "Managing Principal Comments", 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section II: Design', 'Coordination', 'Employee Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'Field Review', 'Completes field surveys', 'check_box', [2, 3, 4, 5 , 6, 7]],
	['Section III: Contract Administration', 'Field Review', 'Conducts general review of the building and provides direction for specific items to be reviewed', 'check_box', [4, 5, 6, 7]],
	['Section III: Contract Administration', 'Field Review', 'Directs field surveys - as found conditions', 'check_box', [4, 5, 6, 7]],
	['Section III: Contract Administration', 'Field Review', 'Directs site visits/reviews/warranty inspections', 'check_box', [4, 5, 6, 7]],
	['Section III: Contract Administration', 'Field Review', 'Complies with safety regulations', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'Field Review', 'Accurately records required information', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'Field Review', 'Able to transfer information to supervisor', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'Field Review', "Managing Principal Comments", 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'Field Review', 'Employee Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'RFIs', 'Comprehends questions', 'check_box', [3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'RFIs', 'Reviews current design to determine extent of issue', 'check_box', [3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'RFIs', 'Provides clear and concise responses in a timely manner', 'check_box', [3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'RFIs', 'Documents RFI in accordance to CEL standards', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'RFIs', "Managing Principal Comments", 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'RFIs', 'Employee Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'Contract Administration', 'Able to determine if shop drawings meet specifications ', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Able to determine if maintenance manual meet specifications', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Responds in a timely manner', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Documents in accordance with CEL standards', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Provides clear/concise response in shop drawings and identifies what is required', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Able to determine if contractor has met contractual obligations - completeness and qualified', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Able to make recommendations for preferred contractor', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Able to track according to CEL standards', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Able to create clear and concise CCNs, Site Instructions and Addendas', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Issue in a timely manner', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Reviews costing and determines appropriateness and quantity', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Able to determine if construction is in accordance to documents', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Creates clear and concise site visit reports', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Issues SVR and deficiency lists in a timely manner', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Effectively evaluates project completeness for progress', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Provide feedback to supervisor re: general progress', 'check_box', [3, 4, 5, 6]],
	['Section III: Contract Administration', 'Contract Administration', 'Ensures team members are working effectively', 'check_box', [6]],
	['Section III: Contract Administration', 'Contract Administration', 'Able to assess project progress and identify risk (i.e. delays, improper installation, poor quality construction, etc.)', 'check_box', [7]],
	['Section III: Contract Administration', 'Contract Administration', 'Responsible for ensuring CEL work is done in a timely manner through delegation (SD, SVR)', 'check_box', [7]],
	['Section III: Contract Administration', 'Contract Administration', 'Effectively monitor team members workload and/or shares staff with other teams', 'check_box', [7]],
	['Section III: Contract Administration', 'Contract Administration', "Managing Principal Comments", 'text', [3, 4, 5, 6, 7]],
	['Section III: Contract Administration', 'Contract Administration', 'Employee Comments', 'text', [3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Client Interface', 'Communicates with client in a timely manner', 'check_box', [2, 3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Client Interface', 'Able to communciate effectively both oral and written', 'check_box', [2, 3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Client Interface', 'Checks with client regarding levels of satisfaction', 'check_box', [5, 6, 7]],
	['Section IV: Project Management', 'Client Interface', 'Promotes CEL in a professional manner at all times', 'check_box', [2, 3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Client Interface', 'Reporting project challenges with supervisor', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Client Interface', 'Getting to know client and developing relationships', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Client Interface', 'Working with ESWOs', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Client Interface', 'Able to address project challenges with client', 'check_box', [7]],
	['Section IV: Project Management', 'Client Interface', 'Further develop relationship with goal(s) of client(s) through direct contact', 'check_box', [7]],
	['Section IV: Project Management', 'Client Interface', 'Following up of ESWOs approval and payment', 'check_box', [7]],
	['Section IV: Project Management', 'Client Interface', "Managing Principal Comments", 'text', [2, 3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Client Interface', 'Employee Comments', 'text', [2, 3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Project Management', 'Completes Project Status Manager Reports', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Project Management', 'Completes Extra Service Work Order reports', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Project Management', 'Reports scope of work; and extra fee requests based on client requests or changes to scope for approval of Supervisor', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Project Management', 'Assists in dealing with collection activities', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Project Management', 'Identifies changes to scope', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Project Management', 'Understands project objectives', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Project Management', 'Meets project deadlines', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Project Management', 'Notifies supervisor if issues arise  re: meeting deadlines', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Project Management', 'Keeps project within available hours', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Project Management', 'Holds effective meetings', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Project Management', 'Actively participates in team meetings and prepares meeting mintues for projects chaired by CEL', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Project Management', 'Able to perform staff reviews and provides constructive criticism on performance', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Project Management', 'Able to recognize potential risks to project success', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Project Management', "Managing Principal Comments", 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Project Management', 'Employee Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section IV: Project Management', 'Promotion of Business', 'Ensures client is aware of extra services that CEL provides', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Promotion of Business', 'Builds and maintains client relationships', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Promotion of Business', 'Seeks and develops new clients', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Promotion of Business', 'Keeps clients satisfied', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Promotion of Business', 'Attends client functions', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Promotion of Business', 'Participates in social events with clients (i.e. golf, lunch, theatre, etc.)', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Promotion of Business', "Managing Principal Comments", 'text', [6, 7]],
	['Section IV: Project Management', 'Promotion of Business', 'EmployeeComments', 'text', [6, 7]],
	['Section IV: Project Management', 'Supervisory', "Informs Supervisor of team members' performance", 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', 'Communicates project objectives, schedule and design details to team members', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', 'Assigns appropriate work to team members and provides direction as needed', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', "Monitors team members' progress and performance", 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', "Reviews team members' work for accuracy and completeness", 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', 'Monitors and manages punctuality, attendance and absence of team members', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', 'Ensures team members comply with CEL policies and procedures', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', 'Provides coaching and feedback to team members', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', 'Identifies, addresses and manages performance problems', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', 'Reviews and approves team members time sheets on a weekly basis', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', 'Communicates team, departmental and organizational information to team members', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', 'Provides training and development of team members', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', 'Provides input for performance reviews', 'check_box', [6, 7]],
	['Section IV: Project Management', 'Supervisory', "Managing Principal Comments", 'text', [6, 7]],
	['Section IV: Project Management', 'Supervisory', 'Employee Comments', 'text', [6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Arrives at meetings on time', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Arrives and leaves in accordance with their working schedule', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Attends internal meetings', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Participates in training', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Maintains an organized desk', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Files emails and design files on network', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Follows company project closeout procedures', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Timesheets are completed on time', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Expenses are submitted on time', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Complies with CEL policies and procedures', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Ability to work independently with minimal input from supervisor', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Participates in learning sessions', 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Managing assigned team', 'check_box', [7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Able to provide assistance to team members where possible', 'check_box', [7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Responsible for establishing team size', 'check_box', [7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Able to provide solutions to other PMs and Snr PMs', 'check_box', [7]],
	['Section V: Organization and Health Safety', 'Organizational', "Managing Principal Comments", 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Organizational', 'Employee Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Health and Safety', "Complies with CEL's H&S program", 'check_box', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Health and Safety', "Managing Principal Comments", 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section V: Organization and Health Safety', 'Health and Safety', 'Employee Comments', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section VI: Overall Performance', 'Feedback on Overall Performance Results: How Results Were Achieved', 'Strengths', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section VI: Overall Performance', 'Feedback on Overall Performance Results: How Results Were Achieved', 'Improvement Areas', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section VI: Overall Performance', 'Performance Goals for the Upcoming Year', 'List up to 5 impact goals to  be achieved in the upcoming year', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section VI: Overall Performance', 'Performance Goals for the Upcoming Year', 'Timeframe for completion', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section VI: Overall Performance', 'Choose 1-2 development goals to focus on this year to enhance ', 'Goals', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section VI: Overall Performance', 'Choose 1-2 development goals to focus on this year to enhance ', 'Timeframe for completion', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Section VI: Overall Performance', 'Identify 1-2 career development goals to help make progress for longer-tem ', 'Goals', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Employee Section', 'Please answer each question prior to your meeting with your reviewer:', 'What makes you happy while working at CEL?', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Employee Section', 'Please answer each question prior to your meeting with your reviewer:', 'What frustrates you while working at CEL?', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Employee Section', 'Please answer each question prior to your meeting with your reviewer:', 'What are your career goals for the next 2 years and 5 years.', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Employee Section', 'Please answer each question prior to your meeting with your reviewer:', 'What can your manager do to help you achieve your goals?', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Employee Section', 'Please answer each question prior to your meeting with your reviewer:', 'What are the key items which enable you to do your best work (Work space free of distraction, training, timely input from my Manager, Revit/It Support…)?', 'text', [1, 2, 3, 4, 5, 6, 7]],
	['Employee Section', 'Please answer each question prior to your meeting with your reviewer:', 'What items at CEL are preventing you from doing your best work?', 'text', [1, 2, 3, 4, 5, 6, 7]]

]

sections.each do |section|
	review3.sections.create(title: section[0], portion: section[1])
end

questions.each do |question|
	if question[0] == 'Section I: Drawing Production'
		sec = Section.where(title: 'Section I: Drawing Production').last
	elsif question[0] == 'Section II: Design'
		sec = Section.where(title: 'Section II: Design').last
	elsif question[0] == 'Section III: Contract Administration'
		sec = Section.where(title: 'Section III: Contract Administration').last
	elsif question[0] == 'Section IV: Project Management'
		sec = Section.where(title: 'Section IV: Project Management').last
	elsif question[0] == 'Section V: Organization and Health Safety'
		sec = Section.where(title: 'Section V: Organization and Health Safety').last	
	elsif question[0] == 'Section VI: Overall Performance'
		sec = Section.where(title: 'Section VI: Overall Performance').last
	elsif question[0] == 'Employee Section'
		sec = Section.where(title: 'Employee Section').last
	end
	q = Question.create(section_id: sec.id, subsection: question[1], question_text: question[2], question_type: question[3])
	question[4].each do |level|
		QuestionJobLevel.create(question_id: q.id, job_level: level)
	end 	
end