require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe IndividualReviewsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # IndividualReview. As you add validations to IndividualReview, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IndividualReviewsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all individual_reviews as @individual_reviews" do
      individual_review = IndividualReview.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:individual_reviews)).to eq([individual_review])
    end
    it "assigns @users to all user for which current_user authored review" do
      user1 = create(:user)
      user2 = create(:user)
      current_user = user1
      ir = create(:individual_review, reviewer_id: user1.id)
    end
  end

  describe "GET #show" do
    it "assigns the requested individual_review as @individual_review" do
      individual_review = IndividualReview.create! valid_attributes
      get :show, params: {id: individual_review.to_param}, session: valid_session
      expect(assigns(:individual_review)).to eq(individual_review)
    end
  end

  describe "GET #new" do
    it "assigns a new individual_review as @individual_review" do
      get :new, params: {}, session: valid_session
      expect(assigns(:individual_review)).to be_a_new(IndividualReview)
    end
  end

  describe "GET #edit" do
    it "assigns the requested individual_review as @individual_review" do
      individual_review = IndividualReview.create! valid_attributes
      get :edit, params: {id: individual_review.to_param}, session: valid_session
      expect(assigns(:individual_review)).to eq(individual_review)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new IndividualReview" do
        expect {
          post :create, params: {individual_review: valid_attributes}, session: valid_session
        }.to change(IndividualReview, :count).by(1)
      end

      it "assigns a newly created individual_review as @individual_review" do
        post :create, params: {individual_review: valid_attributes}, session: valid_session
        expect(assigns(:individual_review)).to be_a(IndividualReview)
        expect(assigns(:individual_review)).to be_persisted
      end

      it "redirects to the created individual_review" do
        post :create, params: {individual_review: valid_attributes}, session: valid_session
        expect(response).to redirect_to(IndividualReview.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved individual_review as @individual_review" do
        post :create, params: {individual_review: invalid_attributes}, session: valid_session
        expect(assigns(:individual_review)).to be_a_new(IndividualReview)
      end

      it "re-renders the 'new' template" do
        post :create, params: {individual_review: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested individual_review" do
        individual_review = IndividualReview.create! valid_attributes
        put :update, params: {id: individual_review.to_param, individual_review: new_attributes}, session: valid_session
        individual_review.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested individual_review as @individual_review" do
        individual_review = IndividualReview.create! valid_attributes
        put :update, params: {id: individual_review.to_param, individual_review: valid_attributes}, session: valid_session
        expect(assigns(:individual_review)).to eq(individual_review)
      end

      it "redirects to the individual_review" do
        individual_review = IndividualReview.create! valid_attributes
        put :update, params: {id: individual_review.to_param, individual_review: valid_attributes}, session: valid_session
        expect(response).to redirect_to(individual_review)
      end
    end

    context "with invalid params" do
      it "assigns the individual_review as @individual_review" do
        individual_review = IndividualReview.create! valid_attributes
        put :update, params: {id: individual_review.to_param, individual_review: invalid_attributes}, session: valid_session
        expect(assigns(:individual_review)).to eq(individual_review)
      end

      it "re-renders the 'edit' template" do
        individual_review = IndividualReview.create! valid_attributes
        put :update, params: {id: individual_review.to_param, individual_review: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested individual_review" do
      individual_review = IndividualReview.create! valid_attributes
      expect {
        delete :destroy, params: {id: individual_review.to_param}, session: valid_session
      }.to change(IndividualReview, :count).by(-1)
    end

    it "redirects to the individual_reviews list" do
      individual_review = IndividualReview.create! valid_attributes
      delete :destroy, params: {id: individual_review.to_param}, session: valid_session
      expect(response).to redirect_to(individual_reviews_url)
    end
  end

end
